module.exports = {
  arrowParens: "avoid",
  semi: true,
  tabWidth: 2,
  vueIndentScriptAndStyle: false,
  bracketSpacing: false,
  bracketSameLine: false,
  singleAttributePerLine: true,
  trailingComma: "es5",
  printWidth: 100,
  useTabs: false,
  importOrder: ["^@js/(.*)$"],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: ["@trivago/prettier-plugin-sort-imports"],
};
